export const places = [
  {
    id: 1,
    name: "Kashmir",
    slug: "kashmir",
    image: "/places/KASHMIR.jpg",
    location: "Jammu & Kashmir, North India",
    category: "Nature",
    tagline: "Paradise on Earth",
    description:
      "Kashmir is often called the crown jewel of India, and for good reason. Nestled in the northernmost part of the country, it is a land of breathtaking valleys, snow-covered mountains, and shimmering lakes that seem straight out of a painting. The famous Dal Lake with its iconic shikaras, the lush green meadows of Gulmarg, and the serene beauty of Pahalgam make Kashmir a destination unlike any other. In winter, the entire valley transforms into a snow wonderland perfect for skiing and snowboarding, while spring brings a stunning carpet of blooming tulips and cherry blossoms. Whether you are an adventure seeker or someone looking for peace, Kashmir offers an experience that stays with you forever.",
    bestTimeToVisit: "March to June, December to February",
    duration: "5-6 days",
    highlights: ["Dal Lake", "Gulmarg", "Pahalgam", "Sonamarg", "Tulip Garden"],
    thingsToDo: [
      "Shikara ride on Dal Lake",
      "Skiing in Gulmarg",
      "Trekking in Pahalgam",
      "Visit Mughal Gardens",
      "Try Wazwan cuisine",
    ],
    famousFor: "Houseboats, Saffron, Pashmina shawls",
  },
  {
    id: 2,
    name: "Jaipur",
    slug: "jaipur",
    image: "/places/JAIPUR.jpg",
    location: "Rajasthan, North India",
    category: "Culture",
    tagline: "The Pink City of India",
    description:
      "Jaipur, the capital of Rajasthan, is a city that wears its history proudly on its terracotta-pink walls. Founded in 1727 by Maharaja Jai Singh II, it was one of the first planned cities in India and its grand architecture continues to leave visitors in awe centuries later. The majestic Amber Fort sitting atop a rugged hill, the stunning Hawa Mahal with its 953 intricately carved windows, and the astronomical wonders of Jantar Mantar are just a few of the treasures waiting to be explored. Beyond its monuments, Jaipur is a shopper's paradise — vibrant bazaars overflowing with colorful textiles, precious gemstones, blue pottery, and handcrafted jewelry. The city's cuisine, from dal baati churma to ghewar, is as rich and royal as its heritage.",
    bestTimeToVisit: "October to March",
    duration: "3-4 days",
    highlights: ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar", "Nahargarh Fort"],
    thingsToDo: [
      "Explore Amber Fort on elephant back",
      "Shop at Johari Bazaar",
      "Watch sunset from Nahargarh Fort",
      "Visit City Palace museum",
      "Try authentic Rajasthani thali",
    ],
    famousFor: "Pink architecture, Gemstones, Royal heritage",
  },
  {
    id: 3,
    name: "Manali",
    slug: "manali",
    image: "/places/MANALI.jpg",
    location: "Himachal Pradesh, North India",
    category: "Nature",
    tagline: "Adventure Capital of India",
    description:
      "Perched at an altitude of 2,050 metres in the Kullu Valley, Manali is a paradise for adventure lovers and nature enthusiasts alike. The town is framed by towering Himalayan peaks, dense forests of cedar and pine, and the roaring Beas River that cuts through the valley below. Rohtang Pass, just 51 km away, offers a dramatic landscape of glaciers and snow even in summer, while Solang Valley is a hotspot for paragliding, zorbing, and skiing. Old Manali has a charm of its own — narrow lanes, apple orchards, and the ancient Hadimba Temple tucked quietly inside a cedar forest. The journey from Manali to Leh through one of the highest motorable roads in the world is considered a bucket list experience for every biker and traveler in India.",
    bestTimeToVisit: "October to June",
    duration: "4-5 days",
    highlights: ["Rohtang Pass", "Solang Valley", "Hadimba Temple", "Old Manali", "Beas River"],
    thingsToDo: [
      "River rafting on Beas",
      "Paragliding in Solang Valley",
      "Bike trip to Rohtang Pass",
      "Visit Hadimba Temple",
      "Trek to Jogini Waterfall",
    ],
    famousFor: "Snow adventures, Himalayan views, Apple orchards",
  },
  {
    id: 4,
    name: "Coorg",
    slug: "coorg",
    image: "/places/COORG.jpg",
    location: "Karnataka, South India",
    category: "Nature",
    tagline: "Scotland of India",
    description:
      "Coorg, officially known as Kodagu, is a misty hill station nestled in the Western Ghats of Karnataka and is often called the Scotland of India for its rolling green hills and cool, pleasant climate. The district is blanketed with vast coffee and spice plantations that fill the air with an intoxicating aroma, and walking through these estates is an experience unlike anything else in the country. Abbey Falls, Raja's Seat, and the Namdroling Monastery are must-visit spots that showcase both the natural beauty and cultural richness of the region. Coorg is also home to the Kodava people, a warrior community with a unique culture, cuisine, and traditions that are proudly preserved to this day. The local pork curry and Kadambuttu are dishes every food lover must try on a visit here.",
    bestTimeToVisit: "October to March",
    duration: "3-4 days",
    highlights: ["Abbey Falls", "Raja's Seat", "Namdroling Monastery", "Dubare Elephant Camp", "Talakaveri"],
    thingsToDo: [
      "Coffee plantation walk",
      "White water rafting in Barapole",
      "Elephant interaction at Dubare",
      "Trek to Tadiandamol peak",
      "Visit Bylakuppe Buddhist monastery",
    ],
    famousFor: "Coffee plantations, Misty hills, Kodava culture",
  },
  {
    id: 5,
    name: "Amritsar",
    slug: "amritsar",
    image: "/places/AMRITSAR.jpg",
    location: "Punjab, North India",
    category: "Culture",
    tagline: "City of the Golden Temple",
    description:
      "Amritsar is the spiritual heart of the Sikh community and one of the most sacred cities in all of India. At its center sits the breathtaking Harmandir Sahib, popularly known as the Golden Temple — a gleaming structure of marble and gold that floats serenely on the holy Amrit Sarovar lake and draws millions of devotees and tourists every year. The langar at the Golden Temple, where free meals are served to over 100,000 people daily regardless of religion or background, is a humbling and deeply moving experience. Just 30 km away lies the Wagah Border, where the daily flag-lowering ceremony between India and Pakistan is a thrilling display of patriotism that sends chills down your spine. Amritsar's food scene is legendary — the city is famous for its buttery amritsari kulcha, chole, lassi, and the iconic makki di roti with sarson da saag.",
    bestTimeToVisit: "October to March",
    duration: "2-3 days",
    highlights: ["Golden Temple", "Wagah Border", "Jallianwala Bagh", "Durgiana Temple", "Partition Museum"],
    thingsToDo: [
      "Attend prayer at Golden Temple at dawn",
      "Watch Wagah Border ceremony",
      "Visit Jallianwala Bagh memorial",
      "Eat at Kesar Da Dhaba",
      "Explore Partition Museum",
    ],
    famousFor: "Golden Temple, Punjabi cuisine, Wagah Border ceremony",
  },
  {
    id: 6,
    name: "Mumbai",
    slug: "mumbai",
    image: "/places/MUMBAI.jpg",
    location: "Maharashtra, West India",
    category: "City",
    tagline: "The City That Never Sleeps",
    description:
      "Mumbai is India's maximum city — a relentless, electric, and endlessly fascinating metropolis that is home to over 20 million people and millions of dreams. It is the financial capital of India, the home of Bollywood, and a melting pot of cultures, cuisines, and communities that somehow coexist in beautiful chaos. The iconic Gateway of India standing proudly by the Arabian Sea, the bustling streets of Colaba, the art deco buildings of Marine Drive, and the dharavi lanes that inspired a Hollywood film — every corner of this city has a story to tell. Mumbai's street food culture is legendary, from vada pav and pav bhaji to bhel puri on Chowpatty Beach at sunset. The city pulses with an energy that is uniquely its own — whether you are watching local trains rush by, exploring the nightlife of Bandra, or simply sitting by the sea, Mumbai has a way of making you feel completely alive.",
    bestTimeToVisit: "November to February",
    duration: "3-4 days",
    highlights: ["Gateway of India", "Marine Drive", "Elephanta Caves", "Bandra-Worli Sea Link", "Dharavi"],
    thingsToDo: [
      "Watch sunset at Marine Drive",
      "Take ferry to Elephanta Caves",
      "Explore Colaba Causeway market",
      "Try vada pav at a local stall",
      "Visit Bollywood studios",
    ],
    famousFor: "Bollywood, Street food, Financial hub, Colonial architecture",
  },
  {
    id: 7,
    name: "Goa",
    slug: "goa",
    image: "/places/GOA.jpg",
    location: "Goa, West India",
    category: "Beach",
    tagline: "India's Beach Paradise",
    description:
      "Goa is India's smallest state but packs more personality than places ten times its size. Stretching along 105 km of stunning Arabian Sea coastline, it is a place where golden beaches, swaying palm trees, and a laid-back attitude define everyday life. North Goa is vibrant and energetic — Baga, Calangute, and Anjuna beaches are packed with beach shacks, water sports, and nightlife that goes on till dawn. South Goa, on the other hand, is quieter and more serene, with pristine beaches like Palolem and Agonda that feel almost untouched. Beyond the beaches, Goa has a remarkable Portuguese heritage visible in its whitewashed churches, colorful villas, and the UNESCO-listed Basilica of Bom Jesus. The cuisine is a delicious blend of Indian and Portuguese influences — Goan fish curry, prawn balchão, and bebinca dessert are experiences every food lover must have.",
    bestTimeToVisit: "November to February",
    duration: "4-5 days",
    highlights: ["Baga Beach", "Dudhsagar Falls", "Basilica of Bom Jesus", "Anjuna Flea Market", "Palolem Beach"],
    thingsToDo: [
      "Water sports at Baga Beach",
      "Visit Dudhsagar waterfalls",
      "Explore Old Goa churches",
      "Shop at Anjuna flea market",
      "Try Goan seafood thali",
    ],
    famousFor: "Beaches, Nightlife, Portuguese heritage, Seafood",
  },
  {
    id: 8,
    name: "Lakshadweep",
    slug: "lakshadweep",
    image: "/places/LAKSHADWEEP-ISLANDS.jpg",
    location: "Lakshadweep, Arabian Sea",
    category: "Beach",
    tagline: "India's Hidden Island Gem",
    description:
      "Lakshadweep is India's best kept secret — a tiny archipelago of 36 coral islands scattered across the turquoise waters of the Arabian Sea, lying about 200 to 440 km off the coast of Kerala. With a total land area of just 32 square kilometres, it is India's smallest union territory, yet what it lacks in size it more than makes up for in sheer natural beauty. The lagoons here are impossibly blue, the coral reefs are among the most pristine in Asia, and the white sand beaches are so clean and empty they feel like they belong to you alone. Agatti, Bangaram, and Kadmat islands are the most popular among visitors, offering world-class snorkelling, scuba diving, and kayaking in waters that are crystal clear down to several metres. Tourism here is strictly regulated to protect the fragile ecosystem, which means the islands remain largely unspoilt and genuinely off the beaten path.",
    bestTimeToVisit: "October to May",
    duration: "4-6 days",
    highlights: ["Agatti Island", "Bangaram Atoll", "Kadmat Beach", "Coral Reefs", "Minicoy Island"],
    thingsToDo: [
      "Scuba diving in coral reefs",
      "Glass bottom boat ride",
      "Snorkelling in lagoons",
      "Kayaking through islands",
      "Visit tuna canning factory in Minicoy",
    ],
    famousFor: "Coral reefs, Pristine lagoons, Water sports, Unspoilt beaches",
  },
  {
    id: 9,
    name: "Udaipur",
    slug: "udaipur",
    image: "/places/UDAIPUR.jpg",
    location: "Rajasthan, North India",
    category: "Culture",
    tagline: "The City of Lakes",
    description:
      "Udaipur is perhaps the most romantic city in all of India — a shimmering jewel of lakes, palaces, and havelis nestled in the Aravalli Hills of southern Rajasthan. Founded in 1559 by Maharana Udai Singh II, the city was built around a series of interconnected lakes that give it a magical quality, especially at golden hour when the palaces reflect off the still water. The City Palace, one of the largest palace complexes in Rajasthan, towers over Lake Pichola and houses a remarkable collection of royal artifacts, paintings, and architecture spanning several centuries. The Lake Palace, seemingly floating in the middle of the lake, is one of the most photographed buildings in India and now operates as a luxury hotel. Udaipur's narrow old city lanes are a delight to wander through — full of art galleries, rooftop cafes with panoramic lake views, and artisans crafting miniature paintings that the city has been famous for since the Mughal era.",
    bestTimeToVisit: "September to March",
    duration: "3-4 days",
    highlights: ["City Palace", "Lake Pichola", "Jag Mandir", "Saheliyon ki Bari", "Vintage Car Museum"],
    thingsToDo: [
      "Boat ride on Lake Pichola",
      "Explore City Palace museum",
      "Watch cultural show at Bagore Ki Haveli",
      "Shop for miniature paintings",
      "Rooftop dinner overlooking the lake",
    ],
    famousFor: "Lake palaces, Romantic ambience, Rajput architecture, Miniature paintings",
  },
];

export const getPlaceBySlug = (slug) => {
  return places.find((place) => place.slug === slug) || null;
};

export const getPlacesByCategory = (category) => {
  return places.filter((place) => place.category === category);
};